[package]
name = "ddnn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
core_affinity = "0.8.3"
crossbeam-channel = "0.5.15"
memchr = "2"

[profile.release]
debug = true
lto = "thin"
codegen-units = 1

[profile.profiling]
inherits = "release"
strip = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3"

[[bench]]
name = "throughput"
harness = false
